version: '3'
services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: microservices
      MARIADB_USER: root
    ports:
      - '3306:3306'